name: 'Install pytorch and pytorch-geometric'
description: 'Installs a few common dependencies'
inputs:
  torch-verison:
    description: 'Version of pytorch to install'
    required: true
    default: '1.9.1'
  pyg-verison:
    description: 'Version of pytorch-geometric to install'
    required: true
    default: '1.9.1'
  cuda:
    description: 'Which device type to install pytorch for'
    required: true
    default: 'cpu'
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: |
        pip install torch==${{ inputs.torch-verison }}+${{ inputs.cuda }} -f https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install torch-cluster -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+${{ inputs.cuda }}.html
        pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+${{ inputs.cuda }}.html
        pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+${{ inputs.cuda }}.html
        pip install torch-spline-conv -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+${{ inputs.cuda }}.html
        pip install torch-geometric==${{ inputs.pyg-verison }}
      shell: bash