name: 'Install graphnet'
description: 'Installs graphnet package'

inputs:
  editable:
    description: "Whether to install graphnet as editable"
    required: true
    default: false
  extras:
    description: "Extras flags for pip installation of graphnet"
    required: true
    default: "[develop,torch]"

runs:
  using: "composite"
  steps:
    - name: Infer installation flags
      run: |
        PIP_FLAGS=`[[ ${{ inputs.editable }} =~ (T|t)rue ]] && printf "%s\n" "-e" || echo " "`
        echo "PIP_FLAGS=${PIP_FLAGS}" >> $GITHUB_ENV
      shell: bash
    - name: Install dependencies
      run: |
        pip install --upgrade 'pip>=20,<22.1'
        pip install wheel setuptools==59.5.0
      shell: bash
    - name: Install package
      run: |
        pip install ${{ env.PIP_FLAGS }} -r requirements/torch_cpu.txt .${{ inputs.extras }}
      shell: bash
