# This is a simple workflow to check that all modified files satisfy code
# quality requirements
name: Code quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push and PRs
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  files:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.setvar.outputs.all }}
      python: ${{ steps.setvar.outputs.python }}
    steps:
      - uses: actions/checkout@v2
        #with:
        #  fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Save to output
        id: setvar
        run: |
          all_files=${{ steps.changed-files.outputs.all_changed_files }}
          echo ">> $all_files"
          python_files=$(grep -ow "[^ ]*\.py[^ ]*" <<<"$all_files")
          echo ">> $python_files"
          echo "all=$all_files" >> $GITHUB_OUTPUT
          echo "python=$python_files" >> $GITHUB_OUTPUT

  black:
    needs: [ files ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        uses: ./.github/actions/install-cpu
      - name: Run black
        run: |
          echo ${{needs.files.outputs.python}}
          black ${{needs.files.outputs.python}} --check --diff --config black.toml


