# This is a simple workflow to check that all modified files satisfy code
# quality requirements
name: Code quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push and PRs
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.setvar.outputs.all }}
      python: ${{ steps.setvar.outputs.python }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Save to output
        id: setvar
        run: |
          all_files="${{ steps.changed-files.outputs.all_changed_files }}"
          python_files="$(grep -ow '[^ ]*\.py[^ ]*' <<<'${{ steps.changed-files.outputs.all_changed_files }}' | tr '\n' ' ')"

          echo all="$all_files" >> $GITHUB_OUTPUT
          echo python="$python_files" >> $GITHUB_OUTPUT

  pre-commit:
    name: Pre-commit - ${{ matrix.hook }}
    needs: [ files ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook: ["black", "flake8", "docformatter", "pydocstyle", "mypy"]
    steps:
      - uses: actions/checkout@v3
      - name: Install package
        uses: ./.github/actions/install-cpu
      - name: Run ${{ matrix.hook }}
        run: |
          pre-commit run ${{ matrix.hook }} --files ${{ needs.files.outputs.python }}
