# This is a simple workflow to check that all modified files satisfy code
# quality requirements
name: Code quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push and PRs
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  files:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.setvar.outputs.all }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: ''

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all }}; do
            echo "$file was changed"
          done

      - name:
        id: setvar
        run: |
          echo "::set-output name=all::${{ steps.changed-files.outputs.all }};"

  black:
    needs: [ files ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        uses: ./.github/actions/install-cpu
      - name: Run black
        run: |
          echo ${{needs.files.outputs.all}}
          black ${{needs.files.outputs.all}} --check --diff --config black.toml


