name: docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ container ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TEST_TAG: asogaard/graphnet-test:test
  LATEST_TAG: asogaard/graphnet-test:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{ defaultContext }}:docker"
          push: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{ defaultContext }}:docker"
          push: true
          tags: ${{ env.LATEST_TAG }}
