# This is a simple workflow to automatically generate API docs
name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main branch
  push:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install package
        uses: ./.github/actions/install
      - name: Build documentation
        run: |
          cd docs
          mkdir -p source/_static
          scp ../paper/flowchart.png source/_static/
          sphinx-apidoc -M -f -o source/api ../src/
          sphinx-apidoc -M -f -o source/examples/01_icetray ../examples/01_icetray/
          sphinx-apidoc -M -f -o source/examples/02_data ../examples/02_data/
          sphinx-apidoc -M -f -o source/examples/03_weights ../examples/03_weights/
          sphinx-apidoc -M -f -o source/examples/04_training ../examples/04_training/
          sphinx-apidoc -M -f -o source/examples/05_pisa ../examples/05_pisa/
          make html
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: docs/build/html  # The folder the action should deploy.
          git-config-email: andreas.sogaard@gmail.com
          git-config-name: Andreas Søgaard
