# This is a simple workflow to run linting and produce a badges
name: lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    paths-ignore: [ misc/badges/ ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ misc/badges/ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: |
          pwd
          ls -lart
      - name: Install dependencies
        uses: .github/actions/install-torch
      - name: Install package
        run: |
          pip install .[develop]
      - name: Run pylint
        run: |
          pylint src/graphnet tests/*.py --exit-zero | tee results_pylint.txt
      - name: Generate badge
        run: |
          grep rated < results_pylint.txt | sed 's/.* at //g;s/\/.*//g' | xargs -I {} anybadge -f pylint.svg -v {} pylint
          mkdir -p misc/badges/
          mv pylint.svg misc/badges/
      - name: Configure git
        run: |
          git config user.email "andreas.sogaard@gmail.com"
          git config user.name "Andreas Søgaard"
          git status
      - name: Stage badges
        run: |
          git add -f misc/badges/
      - name: Commit and push changes
        run: |
          git commit -m "Auto-updating lint badge" > /dev/null && git push origin ${GITHUB_REF##*/} || echo "Nothing to push"
